### ISSUE TITLE
Extended shutdown delay of JVM with JPype >= 1.0.0

### ISSUE THREAD

**Issue by John-Hennig** [John-Hennig/MPh#1]
MPh depends on the Python-to-Java bridge [JPype](https://github.com/jpype-project/jpype). As of JPype 1.0.0, released two days ago, the shutdown of the Java virtual machine (JVM) seems to be inexplicably delayed at the end of the Python session. At least under certain circumstances. Apparently if, and only if, the Comsol client has already loaded a model into memory, but not otherwise.

To corroborate this, what follows is the log output from runs of the `test_client` script, as found in the `tests` folder of the repository. Except that, for the sake of clarity, all unit tests after the third one, `test_load()`, were deactivated (commented out), as they add no further insight.

With [JPype 0.7.5](https://github.com/jpype-project/jpype/releases/tag/v0.7.5), the previous stable release, the output is this:
```
$ python test_client.py log
[22:20:49.988] Checking registry node "SOFTWARE\Comsol\COMSOL55".
[22:20:49.988] Checking installation folder "C:\programs\Comsol".
[22:20:50.220] Reported version info is "COMSOL Multiphysics 5.5.0.359".
[22:20:50.220] Assigned name "5.5" to this installation.
[22:20:50.220] JPype version is 0.7.5.
[22:20:50.220] Starting Java virtual machine.
[22:20:50.675] Java virtual machine has started.
[22:20:50.675] Initializing stand-alone client.
[22:20:52.061] Stand-alone client initialized.
[22:20:52.527] Running on 1 processor core.
[22:20:52.527] Loading model "capacitor.mph".
[22:21:03.076] Finished loading model.
[22:21:03.076] Shutting down the Java virtual machine.
[22:21:03.076] Java virtual machine has shut down.
```

Here, the JVM shuts down pretty much immediately, no delay whatsoever.

With the newer release, [JPype 1.0.0](https://github.com/jpype-project/jpype/releases/tag/1.0.0), however, the same test runs like this:
```
$ python test_client.py log
[22:21:52.751] Checking registry node "SOFTWARE\Comsol\COMSOL55".
[22:21:52.751] Checking installation folder "C:\programs\Comsol".
[22:21:52.999] Reported version info is "COMSOL Multiphysics 5.5.0.359".
[22:21:52.999] Assigned name "5.5" to this installation.
[22:21:53.014] JPype version is 1.0.0.
[22:21:53.014] Starting Java virtual machine.
[22:21:54.572] Java virtual machine has started.
[22:21:54.572] Initializing stand-alone client.
[22:21:55.981] Stand-alone client initialized.
[22:21:56.265] Running on 1 processor core.
[22:21:56.280] Loading model "capacitor.mph".
[22:22:06.082] Finished loading model.
[22:22:06.082] Shutting down the Java virtual machine.
[22:23:06.044] Java virtual machine has shut down.
```

There is now a delay of almost exactly one minute (some tens of milliseconds less) between telling the JVM to shut down and it actually doing so. This is not just a usability issue, but also a performance hindrance when distributing simulation runs over multiple external worker processes.

The delay does not occur if the `test_load()` unit test, which loads a Comsol model into the client's memory, is deactivated:
```
$ python test_client.py log
[22:23:53.303] Checking registry node "SOFTWARE\Comsol\COMSOL55".
[22:23:53.303] Checking installation folder "C:\programs\Comsol".
[22:23:53.534] Reported version info is "COMSOL Multiphysics 5.5.0.359".
[22:23:53.534] Assigned name "5.5" to this installation.
[22:23:53.534] JPype version is 1.0.0.
[22:23:53.534] Starting Java virtual machine.
[22:23:55.070] Java virtual machine has started.
[22:23:55.070] Initializing stand-alone client.
[22:23:56.511] Stand-alone client initialized.
[22:23:56.914] Running on 1 processor core.
[22:23:56.914] Shutting down the Java virtual machine.
[22:23:56.930] Java virtual machine has shut down.
```

Again, the shutdown is pretty much immediate, also with the newer version of JPype.

This means that JPype alone cannot be the culprit. It must have something to do with the inner workings (memory management or something) of the Comsol client. Or, unlikely but not impossible either, something inside MPh's code base.

**Comment by John-Hennig** [comment]
Until this issue is resolved, or a work-around discovered, I will peg MPh to require JPype 0.7.5.

Unfortunately, as JPype 0.7.5 does not work with Python 3.8.4 (jpype-project/jpype#787) or, almost guaranteed, newer, this means the Python versions supported by MPh are, until further notice, 3.8.3 or older — and 3.6.0 or later, as before.

This issue may, or may not, be related to how JPype handles shutdowns of the JVM (jpype-project/jpype#778). I do not have a qualified opinion as to whether or not that is the case. Just mentioning it on account of the two issues' similarity, if only in name.

**Comment by Thrameos** [comment]
Did you try instrumenting the shutdown sequence on JPype to see which step in the process it failed in.   The whole process of shutting down is in JPypeContext.   It could be that the failure is a waiting on a piece of user code.

**Comment by John-Hennig** [comment]
Yeah, from what I can tell at first glance, there are a couple of calls to `Thread.sleep()` in `JPypeContext` that *may* add up to a round minute. I know very little Java, so might not get very far, but will give this a shot. Thanks a lot for your feedback.

**Comment by Thrameos** [comment]
I can give you some assistance if you need it.  Basically all you have to do here is find the procedure "org.jpype.JPypeContext.shutdown" and add a System.out.println in front of each of the sections in the shutdown.   You can use the project/jpype_java directory to call "ant jar" and copy the result from project/jpype_java/dist to org.jpype.jar some place in your application space.  Then add that jar to your startJVM classpath.  This will allow you to test withing recompiling the whole JPype code.   You can use this trick to quickly isolate where in the process it is pausing.

**Comment by John-Hennig** [comment]
Status update...

So I figured out how to run JPype from source, which on Windows requires a whopping 10 GB worth of Visual Studio. And also a JDK to `--enable-build-jar`. And I did `--enable-tracing` while I was at it.

I've also learned how to start Comsol through JPype on Linux (Ubuntu 18.04 LTS). Which was on my to-do list anyway. I would like to support Linux eventually.

Bottom line: This curious 60-second delay also occurs on Linux, same way as on Windows. That is, in JPype 1.0.1, but not in JPype 0.7.5. It's nothing inside `org.jpype.JPypeContext.shutdown`. Practically no time is lost between entering and exiting that function. It happens *right before* that function call. According to the trace, as the line `m_JavaVM->DestroyJavaVM()` in `jp_context.cpp` is executed.

Meanwhile, I've noticed that the delay seems to be introduced, not by initiating the shutdown sequence, but rather by loading the Comsol model. That is, that's when the 60 seconds start to tick down. Comsol internals are a black box to me, so no idea how and why that would happen. But importantly, this means it may not be that big a usability issue after all. Most computer simulations run much longer than a minute, and as long as there's a quick shutdown at the end of it, this issue would not be noticeable. I'll do some testing to corroborate that, and would then upgrade to the latest JPype.

**Comment by Thrameos** [comment]
Thanks for keeping me posted.  Sounds like we wont need to go into how to do a dump of active threads to find out where the time out occurs.  

Perhaps what is happening is the old JPype did not actual complete the load, but in fact terminated the load prematurely.  That would explain what you see.  The new version doesn't advance to shutdown until the last non-deamon thread is complete.   So either Comsol internally has a thread with service life of once a minute (possible) or its load command initiates a process in a worker thread which doesn't complete for a minute.

**Comment by John-Hennig** [comment]
I would think it's the latter. The first thing would probably have been noticeable in a typical workflow. I guess.

> Sounds like we wont need to go into how to do a dump of active threads to find out where the time out occurs.

Hah, I dodged a bullet there. ;-) I'm in over my head with all these internals as it is. And VERY glad I can just piggyback off your excellent work.

**Comment by John-Hennig** [comment]
"Fixed" this in latest release (0.7.6) by brute-forcing the shutdown of the Java machine. This is a work-around, and it's not "clean", but supporting the latest Python versions was more important at this point.

**Comment by Thrameos** [comment]
I suppose the other option would be to try to send an interrupt using sigint when you want to shutdown to try to get a user thread to recognize a break in operation is required.   You would need to scan the list of threads and see if one is associated with comsolve then try to set Thread.interrupt.   There is code in the JPypeContext that will print all threads (giving you a handle), which you should be able to send interrupt with.  

Not sure how clean that would be either as Java interrupts are pretty crude.   They will only break out wait operations and the thread has the option of handling it and proceeding.

**Comment by John-Hennig** [comment]
Thanks for the hint, I will give this another shot (one of these days). The Comsol client may also have an access functions for the list of threads. I've played around with some of them to try to shut down the JVM gracefully, but no success so far as these things are not documented on the Comsol side. Two scripts I used to drill down on this are now in the repo's `sandbox` folder.
