### ISSUE TITLE
Make search for installation folder case-insensitive on Linux

### ISSUE THREAD

**Issue by ThibautJacqmin** [John-Hennig/MPh#31]
Thanks for this great work, it works very well ! I just propose to make the Comsol installation folder search case-insensitive. In my case, the folder name is COMSOL56. A workaround, which is maybe not the most elegant is 

    folders = []
    for dirname in ['Comsol', 'COMSOL', 'comsol']:
        item = [item for item in Path('/usr/local').glob(f'{dirname}*') if item.is_dir()]
        if item:
            folders.append(item[0])

line 209 of discovery.py.

**Comment by John-Hennig** [comment]
Yes, the discovery mechanism only checks the default locations on Linux, which is `comsol56` in lower case inside `/usr/local` according to the Comsol documentation. Did you change the installation folder's name when you ran the installer?

I'll make the search case-insensitive in the next release. Though I will probably also add a note in the Installation chapter of the documentation that on Linux and macOS default install locations are assumed, as there is no good way to find the folder if users put it in an arbitrary location. (As opposed to Windows, there the installer leaves that information in the Registry.)
