### ISSUE TITLE
model.save() can fail with current master

### ISSUE THREAD

**Issue by max3-2** [John-Hennig/MPh#32]
John,

currently model save can fail if the argument is a single string, e.g. `model.save('test.mph')` - this occurs due to 
```python
        # Possibly deduce format from file ending.
        if format is None:
            suffix = path.suffix if path else '.mph'
```
where `path` is str and thus has no suffix. I think either a clear specification that a `pathlib.Path` needs to be supplied (complicated) or a typecast in `model.save()` is needed.

Best

**Comment by John-Hennig** [comment]
That was an oversight, thanks for reporting. I'll fix that before the next release. We just need to coerce `str` to `Path` just like before.
