### ISSUE TITLE
Incompatability when using mix of 32 bit python and 64 bit OS  

### ISSUE THREAD

**Issue by SamF111** [John-Hennig/MPh#4]
Can't read registry when using 32 bit python and 64 bit registry.

Line 72 in backend should be changed to:
main = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, path_main, access=winreg.KEY_READ | winreg.KEY_WOW64_64KEY)

Line 99 should be changed to:
node = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, path_node, 0, winreg.KEY_READ | winreg.KEY_WOW64_64KEY)

https://stackoverflow.com/questions/30932831/winreg-openkey-throws-filenotfound-error-for-existing-registry-keys

This stops the MPh scripts from working.

**Comment by Eify666666** [comment]
i meet this problem.
Traceback (most recent call last):
  File "F:/python project/test_mph/test_model.py", line 268, in <module>
    setup_module()
  File "F:/python project/test_mph/test_model.py", line 27, in setup_module
    client = mph.Client()
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\site-packages\mph\client.py", line 85, in __init__
    main = backend.folder(version)
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\site-packages\mph\backend.py", line 214, in folder
    last = list(versions().keys())[-1]
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\site-packages\mph\backend.py", line 125, in versions
    process = run(f'{path} --version', stdout=PIPE, creationflags=flags)
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)

OSError: [WinError 193] %1 is not a valid Win32 application

python 3.7 64bit
windows10
comsol 5.4

**Comment by Eify666666** [comment]
> i meet this problem.
> Traceback (most recent call last):
> File "F:/python project/test_mph/test_model.py", line 268, in
> setup_module()
> File "F:/python project/test_mph/test_model.py", line 27, in setup_module
> client = mph.Client()
> File "C:\Users\Eify.conda\envs\pytorch160\lib\site-packages\mph\client.py", line 85, in **init**
> main = backend.folder(version)
> File "C:\Users\Eify.conda\envs\pytorch160\lib\site-packages\mph\backend.py", line 214, in folder
> last = list(versions().keys())[-1]
> File "C:\Users\Eify.conda\envs\pytorch160\lib\site-packages\mph\backend.py", line 125, in versions
> process = run(f'{path} --version', stdout=PIPE, creationflags=flags)
> File "C:\Users\Eify.conda\envs\pytorch160\lib\subprocess.py", line 488, in run
> with Popen(*popenargs, **kwargs) as process:
> File "C:\Users\Eify.conda\envs\pytorch160\lib\subprocess.py", line 800, in **init**
> restore_signals, start_new_session)
> File "C:\Users\Eify.conda\envs\pytorch160\lib\subprocess.py", line 1207, in _execute_child
> startupinfo)
> 
> OSError: [WinError 193] %1 is not a valid Win32 application
> 
> python 3.7 64bit
> windows10
> comsol 5.4

I find the reasons and solutions.
There is a space in my path of comsol.
When i retool the comsol, it works.

Here is the same question and solution.
(https://teratail.com/questions/127811)

**Comment by John-Hennig** [comment]
I finally got around to fixing this. I don't really see the point of supporting 32-bit Python, but also see no harm in it. Thanks for your suggestion, it is included in the latest release, 0.7.6.
